/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui;

import bll.DayManager;
import bll.DoctorManager;
import bll.YearMonthManager;
import dto.Day;
import dto.Doctor;
import java.time.YearMonth;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JToggleButton;

/**
 *
 * @author PC
 */
public class pnlDaysOff extends javax.swing.JPanel {

    private final JToggleButton[] arrTgl;
    private final Doctor doctor;

    /**
     * Creates new form pnlDaysOff
     *
     * @param doctor
     */
    public pnlDaysOff(Doctor doctor) {
        initComponents();
        arrTgl = new JToggleButton[]{
            tgl1, tgl2, tgl3, tgl4, tgl5,
            tgl6, tgl7, tgl8, tgl9, tgl10,
            tgl11, tgl12, tgl13, tgl14, tgl15,
            tgl16, tgl17, tgl18, tgl19, tgl20,
            tgl21, tgl22, tgl23, tgl24, tgl25,
            tgl26, tgl27, tgl28, tgl29, tgl30,
            tgl31
        };
        this.doctor = doctor;
    }

    @Override
    public void addNotify() {
        super.addNotify();

        YearMonth ym = YearMonthManager.getNextYearMonth();
        int daysInMonth = ym.lengthOfMonth();

        lblDaysOff.setText(String.format("Chọn các ngày nghỉ cho tháng %d năm %d", ym.getMonthValue(), ym.getYear()));
        if (daysInMonth < 31) {
            tgl31.setEnabled(false);
        }
        if (daysInMonth < 30) {
            tgl30.setEnabled(false);
        }
        if (daysInMonth < 29) {
            tgl29.setEnabled(false);
        }

        List<Day> daysOff = doctor.daysOff();
        for (Day day : daysOff) {
            arrTgl[day.id() - 1].setSelected(true);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblDaysOff = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        tgl1 = new javax.swing.JToggleButton();
        tgl2 = new javax.swing.JToggleButton();
        tgl3 = new javax.swing.JToggleButton();
        tgl4 = new javax.swing.JToggleButton();
        tgl5 = new javax.swing.JToggleButton();
        tgl6 = new javax.swing.JToggleButton();
        tgl7 = new javax.swing.JToggleButton();
        tgl8 = new javax.swing.JToggleButton();
        tgl9 = new javax.swing.JToggleButton();
        tgl10 = new javax.swing.JToggleButton();
        tgl11 = new javax.swing.JToggleButton();
        tgl12 = new javax.swing.JToggleButton();
        tgl13 = new javax.swing.JToggleButton();
        tgl14 = new javax.swing.JToggleButton();
        tgl15 = new javax.swing.JToggleButton();
        tgl16 = new javax.swing.JToggleButton();
        tgl17 = new javax.swing.JToggleButton();
        tgl18 = new javax.swing.JToggleButton();
        tgl19 = new javax.swing.JToggleButton();
        tgl20 = new javax.swing.JToggleButton();
        tgl21 = new javax.swing.JToggleButton();
        tgl22 = new javax.swing.JToggleButton();
        tgl23 = new javax.swing.JToggleButton();
        tgl24 = new javax.swing.JToggleButton();
        tgl25 = new javax.swing.JToggleButton();
        tgl26 = new javax.swing.JToggleButton();
        tgl27 = new javax.swing.JToggleButton();
        tgl28 = new javax.swing.JToggleButton();
        tgl29 = new javax.swing.JToggleButton();
        tgl30 = new javax.swing.JToggleButton();
        tgl31 = new javax.swing.JToggleButton();
        btnSave = new javax.swing.JButton();

        setBackground(new java.awt.Color(240, 248, 255));

        lblDaysOff.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        lblDaysOff.setForeground(new java.awt.Color(30, 60, 90));
        lblDaysOff.setText("Các ngày nghỉ");

        jPanel1.setBackground(new java.awt.Color(240, 248, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setLayout(new java.awt.GridLayout(7, 5));

        tgl1.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        tgl1.setText("1");
        jPanel1.add(tgl1);

        tgl2.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        tgl2.setText("2");
        jPanel1.add(tgl2);

        tgl3.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        tgl3.setText("3");
        jPanel1.add(tgl3);

        tgl4.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        tgl4.setText("4");
        jPanel1.add(tgl4);

        tgl5.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        tgl5.setText("5");
        jPanel1.add(tgl5);

        tgl6.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        tgl6.setText("6");
        jPanel1.add(tgl6);

        tgl7.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        tgl7.setText("7");
        jPanel1.add(tgl7);

        tgl8.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        tgl8.setText("8");
        jPanel1.add(tgl8);

        tgl9.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        tgl9.setText("9");
        jPanel1.add(tgl9);

        tgl10.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        tgl10.setText("10");
        jPanel1.add(tgl10);

        tgl11.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        tgl11.setText("11");
        jPanel1.add(tgl11);

        tgl12.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        tgl12.setText("12");
        jPanel1.add(tgl12);

        tgl13.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        tgl13.setText("13");
        jPanel1.add(tgl13);

        tgl14.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        tgl14.setText("14");
        jPanel1.add(tgl14);

        tgl15.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        tgl15.setText("15");
        jPanel1.add(tgl15);

        tgl16.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        tgl16.setText("16");
        jPanel1.add(tgl16);

        tgl17.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        tgl17.setText("17");
        jPanel1.add(tgl17);

        tgl18.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        tgl18.setText("18");
        jPanel1.add(tgl18);

        tgl19.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        tgl19.setText("19");
        jPanel1.add(tgl19);

        tgl20.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        tgl20.setText("20");
        jPanel1.add(tgl20);

        tgl21.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        tgl21.setText("21");
        jPanel1.add(tgl21);

        tgl22.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        tgl22.setText("22");
        jPanel1.add(tgl22);

        tgl23.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        tgl23.setText("23");
        jPanel1.add(tgl23);

        tgl24.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        tgl24.setText("24");
        jPanel1.add(tgl24);

        tgl25.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        tgl25.setText("25");
        jPanel1.add(tgl25);

        tgl26.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        tgl26.setText("26");
        jPanel1.add(tgl26);

        tgl27.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        tgl27.setText("27");
        jPanel1.add(tgl27);

        tgl28.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        tgl28.setText("28");
        jPanel1.add(tgl28);

        tgl29.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        tgl29.setText("29");
        jPanel1.add(tgl29);

        tgl30.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        tgl30.setText("30");
        jPanel1.add(tgl30);

        tgl31.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        tgl31.setText("31");
        jPanel1.add(tgl31);

        btnSave.setBackground(new java.awt.Color(0, 120, 215));
        btnSave.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        btnSave.setForeground(new java.awt.Color(255, 255, 255));
        btnSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/images/floppy-disk-solid.png"))); // NOI18N
        btnSave.setText("Lưu");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblDaysOff)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                    .addComponent(btnSave, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblDaysOff)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnSave)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        List<Integer> daysOff = new ArrayList<>();

        for (int i = 0; i < arrTgl.length; i++) {
            if (arrTgl[i].isSelected()) {
                daysOff.add(i + 1);
            }
        }

        doctor.daysOff().clear();
        doctor.daysOff().addAll(
                DayManager.getNextDays().stream()
                        .filter(day -> daysOff.contains(day.id()))
                        .toList()
        );

        DoctorManager.setDoctors(DoctorManager.getDoctors());

        JOptionPane.showMessageDialog(
                this,
                "Lưu các ngày nghỉ thành công.",
                "Thông báo",
                JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnSaveActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSave;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblDaysOff;
    private javax.swing.JToggleButton tgl1;
    private javax.swing.JToggleButton tgl10;
    private javax.swing.JToggleButton tgl11;
    private javax.swing.JToggleButton tgl12;
    private javax.swing.JToggleButton tgl13;
    private javax.swing.JToggleButton tgl14;
    private javax.swing.JToggleButton tgl15;
    private javax.swing.JToggleButton tgl16;
    private javax.swing.JToggleButton tgl17;
    private javax.swing.JToggleButton tgl18;
    private javax.swing.JToggleButton tgl19;
    private javax.swing.JToggleButton tgl2;
    private javax.swing.JToggleButton tgl20;
    private javax.swing.JToggleButton tgl21;
    private javax.swing.JToggleButton tgl22;
    private javax.swing.JToggleButton tgl23;
    private javax.swing.JToggleButton tgl24;
    private javax.swing.JToggleButton tgl25;
    private javax.swing.JToggleButton tgl26;
    private javax.swing.JToggleButton tgl27;
    private javax.swing.JToggleButton tgl28;
    private javax.swing.JToggleButton tgl29;
    private javax.swing.JToggleButton tgl3;
    private javax.swing.JToggleButton tgl30;
    private javax.swing.JToggleButton tgl31;
    private javax.swing.JToggleButton tgl4;
    private javax.swing.JToggleButton tgl5;
    private javax.swing.JToggleButton tgl6;
    private javax.swing.JToggleButton tgl7;
    private javax.swing.JToggleButton tgl8;
    private javax.swing.JToggleButton tgl9;
    // End of variables declaration//GEN-END:variables
}
