/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

import DAL.DayManager;
import DAL.DoctorManager;
import DTO.Day;
import DTO.Doctor;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.List;
import java.util.stream.Collectors;
import javax.swing.JToggleButton;

/**
 *
 * @author PC
 */
public class pnlDaysOff extends javax.swing.JPanel {

    private final JToggleButton[] arrChk;
    private final Doctor doctor;

    /**
     * Creates new form pnlDaysOff
     *
     * @param doctor
     */
    public pnlDaysOff(Doctor doctor) {
        initComponents();
        arrChk = new JToggleButton[]{
            chk1, chk2, chk3, chk4, chk5,
            chk6, chk7, chk8, chk9, chk10,
            chk11, chk12, chk13, chk14, chk15,
            chk16, chk17, chk18, chk19, chk20,
            chk21, chk22, chk23, chk24, chk25,
            chk26, chk27, chk28, chk29, chk30,
            chk31
        };

        this.doctor = doctor;
    }

    private int getDaysInMonth(int year, int month) {
        switch (month) {
            case 1, 3, 5, 7, 8, 10, 12 -> {
                return 31;
            }
            case 4, 6, 9, 11 -> {
                return 30;
            }
            case 2 -> {
                if ((year % 4 == 0 && year % 100 != 0) || (year % 400 == 0)) {
                    return 29;
                }
                return 28;
            }
        }
        return 0;
    }

    @Override
    public void addNotify() {
        super.addNotify();
        LocalDate date = DayManager.getDays().get(0).date();
        int year = date.getYear();
        int month = date.getMonthValue();
        int daysInMonth = getDaysInMonth(year, month);

        lblMonth.setText(month + " / " + year);
        if (daysInMonth < 31) {
            chk31.setEnabled(false);
        }
        if (daysInMonth < 30) {
            chk30.setEnabled(false);
        }
        if (daysInMonth < 29) {
            chk29.setEnabled(false);
        }

        List<Day> daysOff = doctor.daysOff();
        for (Day day : daysOff) {
            arrChk[day.dayID() - 1].setSelected(true);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnSave = new javax.swing.JButton();
        lblMonth = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        chk1 = new javax.swing.JToggleButton();
        chk2 = new javax.swing.JToggleButton();
        chk3 = new javax.swing.JToggleButton();
        chk4 = new javax.swing.JToggleButton();
        chk5 = new javax.swing.JToggleButton();
        chk6 = new javax.swing.JToggleButton();
        chk7 = new javax.swing.JToggleButton();
        chk8 = new javax.swing.JToggleButton();
        chk9 = new javax.swing.JToggleButton();
        chk10 = new javax.swing.JToggleButton();
        chk11 = new javax.swing.JToggleButton();
        chk12 = new javax.swing.JToggleButton();
        chk13 = new javax.swing.JToggleButton();
        chk14 = new javax.swing.JToggleButton();
        chk15 = new javax.swing.JToggleButton();
        chk16 = new javax.swing.JToggleButton();
        chk17 = new javax.swing.JToggleButton();
        chk18 = new javax.swing.JToggleButton();
        chk19 = new javax.swing.JToggleButton();
        chk20 = new javax.swing.JToggleButton();
        chk21 = new javax.swing.JToggleButton();
        chk22 = new javax.swing.JToggleButton();
        chk23 = new javax.swing.JToggleButton();
        chk24 = new javax.swing.JToggleButton();
        chk25 = new javax.swing.JToggleButton();
        chk26 = new javax.swing.JToggleButton();
        chk27 = new javax.swing.JToggleButton();
        chk28 = new javax.swing.JToggleButton();
        chk29 = new javax.swing.JToggleButton();
        chk30 = new javax.swing.JToggleButton();
        chk31 = new javax.swing.JToggleButton();

        setBackground(new java.awt.Color(240, 248, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(30, 60, 90));
        jLabel1.setText("Chọn các ngày nghỉ cho tháng");

        btnSave.setBackground(new java.awt.Color(0, 120, 215));
        btnSave.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnSave.setForeground(new java.awt.Color(255, 255, 255));
        btnSave.setText("Lưu");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        lblMonth.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblMonth.setForeground(new java.awt.Color(30, 60, 90));
        lblMonth.setText("0");

        jPanel1.setBackground(new java.awt.Color(240, 248, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setLayout(new java.awt.GridLayout(7, 5));

        chk1.setBackground(new java.awt.Color(220, 220, 220));
        chk1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        chk1.setText("1");
        jPanel1.add(chk1);

        chk2.setBackground(new java.awt.Color(220, 220, 220));
        chk2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        chk2.setText("2");
        jPanel1.add(chk2);

        chk3.setBackground(new java.awt.Color(220, 220, 220));
        chk3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        chk3.setText("3");
        jPanel1.add(chk3);

        chk4.setBackground(new java.awt.Color(220, 220, 220));
        chk4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        chk4.setText("4");
        jPanel1.add(chk4);

        chk5.setBackground(new java.awt.Color(220, 220, 220));
        chk5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        chk5.setText("5");
        jPanel1.add(chk5);

        chk6.setBackground(new java.awt.Color(220, 220, 220));
        chk6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        chk6.setText("6");
        jPanel1.add(chk6);

        chk7.setBackground(new java.awt.Color(220, 220, 220));
        chk7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        chk7.setText("7");
        jPanel1.add(chk7);

        chk8.setBackground(new java.awt.Color(220, 220, 220));
        chk8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        chk8.setText("8");
        jPanel1.add(chk8);

        chk9.setBackground(new java.awt.Color(220, 220, 220));
        chk9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        chk9.setText("9");
        jPanel1.add(chk9);

        chk10.setBackground(new java.awt.Color(220, 220, 220));
        chk10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        chk10.setText("10");
        jPanel1.add(chk10);

        chk11.setBackground(new java.awt.Color(220, 220, 220));
        chk11.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        chk11.setText("11");
        jPanel1.add(chk11);

        chk12.setBackground(new java.awt.Color(220, 220, 220));
        chk12.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        chk12.setText("12");
        jPanel1.add(chk12);

        chk13.setBackground(new java.awt.Color(220, 220, 220));
        chk13.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        chk13.setText("13");
        jPanel1.add(chk13);

        chk14.setBackground(new java.awt.Color(220, 220, 220));
        chk14.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        chk14.setText("14");
        jPanel1.add(chk14);

        chk15.setBackground(new java.awt.Color(220, 220, 220));
        chk15.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        chk15.setText("15");
        jPanel1.add(chk15);

        chk16.setBackground(new java.awt.Color(220, 220, 220));
        chk16.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        chk16.setText("16");
        jPanel1.add(chk16);

        chk17.setBackground(new java.awt.Color(220, 220, 220));
        chk17.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        chk17.setText("17");
        jPanel1.add(chk17);

        chk18.setBackground(new java.awt.Color(220, 220, 220));
        chk18.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        chk18.setText("18");
        jPanel1.add(chk18);

        chk19.setBackground(new java.awt.Color(220, 220, 220));
        chk19.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        chk19.setText("19");
        jPanel1.add(chk19);

        chk20.setBackground(new java.awt.Color(220, 220, 220));
        chk20.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        chk20.setText("20");
        jPanel1.add(chk20);

        chk21.setBackground(new java.awt.Color(220, 220, 220));
        chk21.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        chk21.setText("21");
        jPanel1.add(chk21);

        chk22.setBackground(new java.awt.Color(220, 220, 220));
        chk22.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        chk22.setText("22");
        jPanel1.add(chk22);

        chk23.setBackground(new java.awt.Color(220, 220, 220));
        chk23.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        chk23.setText("23");
        jPanel1.add(chk23);

        chk24.setBackground(new java.awt.Color(220, 220, 220));
        chk24.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        chk24.setText("24");
        jPanel1.add(chk24);

        chk25.setBackground(new java.awt.Color(220, 220, 220));
        chk25.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        chk25.setText("25");
        jPanel1.add(chk25);

        chk26.setBackground(new java.awt.Color(220, 220, 220));
        chk26.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        chk26.setText("26");
        jPanel1.add(chk26);

        chk27.setBackground(new java.awt.Color(220, 220, 220));
        chk27.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        chk27.setText("27");
        jPanel1.add(chk27);

        chk28.setBackground(new java.awt.Color(220, 220, 220));
        chk28.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        chk28.setText("28");
        jPanel1.add(chk28);

        chk29.setBackground(new java.awt.Color(220, 220, 220));
        chk29.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        chk29.setText("29");
        jPanel1.add(chk29);

        chk30.setBackground(new java.awt.Color(220, 220, 220));
        chk30.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        chk30.setText("30");
        jPanel1.add(chk30);

        chk31.setBackground(new java.awt.Color(220, 220, 220));
        chk31.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        chk31.setText("31");
        jPanel1.add(chk31);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblMonth)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnSave, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lblMonth))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSave)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        List<Integer> daysOff = new ArrayList<>();

        for (int i = 0; i < arrChk.length; i++) {
            if (arrChk[i].isSelected()) {
                daysOff.add(i + 1);
            }
        }

        doctor.daysOff().clear();
        doctor.daysOff().addAll(DayManager.getDays().stream()
                .filter(day -> daysOff.contains(day.dayID()))
                .collect(Collectors.toList()));

        DoctorManager.setDoctors(DoctorManager.getDoctors());
    }//GEN-LAST:event_btnSaveActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSave;
    private javax.swing.JToggleButton chk1;
    private javax.swing.JToggleButton chk10;
    private javax.swing.JToggleButton chk11;
    private javax.swing.JToggleButton chk12;
    private javax.swing.JToggleButton chk13;
    private javax.swing.JToggleButton chk14;
    private javax.swing.JToggleButton chk15;
    private javax.swing.JToggleButton chk16;
    private javax.swing.JToggleButton chk17;
    private javax.swing.JToggleButton chk18;
    private javax.swing.JToggleButton chk19;
    private javax.swing.JToggleButton chk2;
    private javax.swing.JToggleButton chk20;
    private javax.swing.JToggleButton chk21;
    private javax.swing.JToggleButton chk22;
    private javax.swing.JToggleButton chk23;
    private javax.swing.JToggleButton chk24;
    private javax.swing.JToggleButton chk25;
    private javax.swing.JToggleButton chk26;
    private javax.swing.JToggleButton chk27;
    private javax.swing.JToggleButton chk28;
    private javax.swing.JToggleButton chk29;
    private javax.swing.JToggleButton chk3;
    private javax.swing.JToggleButton chk30;
    private javax.swing.JToggleButton chk31;
    private javax.swing.JToggleButton chk4;
    private javax.swing.JToggleButton chk5;
    private javax.swing.JToggleButton chk6;
    private javax.swing.JToggleButton chk7;
    private javax.swing.JToggleButton chk8;
    private javax.swing.JToggleButton chk9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblMonth;
    // End of variables declaration//GEN-END:variables
}
