/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

import DTO.User;
import java.awt.BorderLayout;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author PC
 */
public class pnlMain extends javax.swing.JPanel {

    private final JFrame frmMain;
    private final JPanel pnlLogin;
    private final User user;

    /**
     * Creates new form pnlMain
     *
     * @param frmMain
     * @param pnlLogin
     * @param user
     */
    public pnlMain(JFrame frmMain, JPanel pnlLogin, User user) {
        initComponents();
        this.frmMain = frmMain;
        this.pnlLogin = pnlLogin;
        this.user = user;
    }

    @Override
    public void addNotify() {
        super.addNotify();
        lblUsername.setText(user.username());
        if (user.role().equals("admin")) {
            btnProfile.setVisible(false);
            btnDaysOff.setVisible(false);
            btnSchedules.setVisible(false);
        } else {
            btnDoctors.setVisible(false);
            btnRooms.setVisible(false);
            btnCreate.setVisible(false);
        }
    }

    private void setLayout(JPanel pnl) {
        pnlMain.removeAll();
        pnlMain.setLayout(new BorderLayout());
        pnlMain.add(pnl, BorderLayout.CENTER);
        pnlMain.revalidate();
        pnlMain.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblUsername = new javax.swing.JLabel();
        btnLogout = new javax.swing.JButton();
        btnProfile = new javax.swing.JButton();
        btnSchedules = new javax.swing.JButton();
        btnDaysOff = new javax.swing.JButton();
        btnCreate = new javax.swing.JButton();
        btnRooms = new javax.swing.JButton();
        btnDoctors = new javax.swing.JButton();
        pnlMain = new javax.swing.JPanel();

        setBackground(new java.awt.Color(240, 248, 255));

        jPanel1.setBackground(new java.awt.Color(240, 248, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(150, 150, 150)));

        lblUsername.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        lblUsername.setForeground(new java.awt.Color(30, 60, 90));
        lblUsername.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUsername.setText("Username");

        btnLogout.setBackground(new java.awt.Color(220, 20, 60));
        btnLogout.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnLogout.setForeground(new java.awt.Color(255, 255, 255));
        btnLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Images/right-to-bracket-solid.png"))); // NOI18N
        btnLogout.setText("Đăng xuất");
        btnLogout.setPreferredSize(new java.awt.Dimension(150, 40));
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        btnProfile.setBackground(new java.awt.Color(100, 149, 237));
        btnProfile.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnProfile.setForeground(new java.awt.Color(255, 255, 255));
        btnProfile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Images/address-card-solid.png"))); // NOI18N
        btnProfile.setText("Hồ sơ");
        btnProfile.setPreferredSize(new java.awt.Dimension(150, 40));
        btnProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProfileActionPerformed(evt);
            }
        });

        btnSchedules.setBackground(new java.awt.Color(100, 149, 237));
        btnSchedules.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnSchedules.setForeground(new java.awt.Color(255, 255, 255));
        btnSchedules.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Images/calendar-solid.png"))); // NOI18N
        btnSchedules.setText("Lịch trực");
        btnSchedules.setPreferredSize(new java.awt.Dimension(150, 40));
        btnSchedules.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSchedulesActionPerformed(evt);
            }
        });

        btnDaysOff.setBackground(new java.awt.Color(100, 149, 237));
        btnDaysOff.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnDaysOff.setForeground(new java.awt.Color(255, 255, 255));
        btnDaysOff.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Images/power-off-solid.png"))); // NOI18N
        btnDaysOff.setText("Ngày nghỉ");
        btnDaysOff.setPreferredSize(new java.awt.Dimension(150, 40));
        btnDaysOff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDaysOffActionPerformed(evt);
            }
        });

        btnCreate.setBackground(new java.awt.Color(100, 149, 237));
        btnCreate.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnCreate.setForeground(new java.awt.Color(255, 255, 255));
        btnCreate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Images/plus-solid.png"))); // NOI18N
        btnCreate.setText("Tạo lịch");
        btnCreate.setPreferredSize(new java.awt.Dimension(150, 40));
        btnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateActionPerformed(evt);
            }
        });

        btnRooms.setBackground(new java.awt.Color(100, 149, 237));
        btnRooms.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnRooms.setForeground(new java.awt.Color(255, 255, 255));
        btnRooms.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Images/hospital-solid.png"))); // NOI18N
        btnRooms.setText("Phòng");
        btnRooms.setPreferredSize(new java.awt.Dimension(150, 40));
        btnRooms.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRoomsActionPerformed(evt);
            }
        });

        btnDoctors.setBackground(new java.awt.Color(100, 149, 237));
        btnDoctors.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnDoctors.setForeground(new java.awt.Color(255, 255, 255));
        btnDoctors.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Images/user-doctor-solid.png"))); // NOI18N
        btnDoctors.setText("Bác sĩ");
        btnDoctors.setPreferredSize(new java.awt.Dimension(150, 40));
        btnDoctors.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDoctorsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblUsername, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnLogout, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                            .addComponent(btnSchedules, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnDaysOff, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnProfile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnCreate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnRooms, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnDoctors, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblUsername)
                .addGap(18, 18, 18)
                .addComponent(btnDoctors, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnRooms, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnCreate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnProfile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnDaysOff, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnSchedules, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlMain.setBackground(new java.awt.Color(240, 248, 255));
        pnlMain.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnlMain.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlMain, javax.swing.GroupLayout.DEFAULT_SIZE, 626, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
        int option = JOptionPane.showConfirmDialog(
                this,
                "Bạn có chắc chắn muốn đăng xuất?",
                "Xác nhận đăng xuất",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE
        );

        if (option == JOptionPane.YES_OPTION) {
            frmMain.setContentPane(pnlLogin);
            revalidate();
            repaint();
            frmMain.pack();
            frmMain.setLocationRelativeTo(null);
        }
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProfileActionPerformed
        // TODO add your handling code here:
        pnlProfile pnl = new pnlProfile(user);
        setLayout(pnl);
    }//GEN-LAST:event_btnProfileActionPerformed

    private void btnSchedulesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSchedulesActionPerformed
        // TODO add your handling code here:
        pnlSchedules pnl = new pnlSchedules(user.doctor());
        setLayout(pnl);
    }//GEN-LAST:event_btnSchedulesActionPerformed

    private void btnDaysOffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDaysOffActionPerformed
        // TODO add your handling code here:
        pnlDaysOff pnl = new pnlDaysOff(user.doctor());
        setLayout(pnl);
    }//GEN-LAST:event_btnDaysOffActionPerformed

    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed
        // TODO add your handling code here:
        pnlCreate pnl = new pnlCreate();
        setLayout(pnl);
    }//GEN-LAST:event_btnCreateActionPerformed

    private void btnRoomsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRoomsActionPerformed
        // TODO add your handling code here:
        pnlRooms pnl = new pnlRooms();
        setLayout(pnl);
    }//GEN-LAST:event_btnRoomsActionPerformed

    private void btnDoctorsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDoctorsActionPerformed
        // TODO add your handling code here:
        pnlDoctors pnl = new pnlDoctors();
        setLayout(pnl);
    }//GEN-LAST:event_btnDoctorsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreate;
    private javax.swing.JButton btnDaysOff;
    private javax.swing.JButton btnDoctors;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnProfile;
    private javax.swing.JButton btnRooms;
    private javax.swing.JButton btnSchedules;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JPanel pnlMain;
    // End of variables declaration//GEN-END:variables
}
