/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui;

import dto.User;

/**
 *
 * @author PC
 */
public class pnlProfile extends javax.swing.JPanel {

    private final User user;

    private void lblLoad() {
        String roomsAllowed = "<html>" + String.join("<br>", user.doctor().roomsAllowed().stream()
                .map(room -> room.name())
                .toList()) + "</html>";

        String daysOff = "<html>" + String.join(", ", user.doctor().daysOff().stream()
                .map(day -> String.valueOf(day.date()))
                .toList()) + "</html>";

        lblDoctorId.setText(String.valueOf(user.doctor().id()));
        lblDoctorName.setText(user.doctor().name());
        lblRoomsAllowed.setText(roomsAllowed);
        lblDatesOff.setText(daysOff);
        lblUsername.setText(user.username());
        lblPassword.setText(user.password());
    }

    /**
     * Creates new form pnlProfile
     *
     * @param user
     */
    public pnlProfile(User user) {
        initComponents();
        this.user = user;
    }

    @Override
    public void addNotify() {
        super.addNotify();
        lblLoad();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lblDoctorId = new javax.swing.JLabel();
        lblDoctorName = new javax.swing.JLabel();
        lblRoomsAllowed = new javax.swing.JLabel();
        lblDatesOff = new javax.swing.JLabel();
        lblUsername = new javax.swing.JLabel();
        lblPassword = new javax.swing.JLabel();

        setBackground(new java.awt.Color(240, 248, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(30, 60, 90));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("THÔNG TIN CÁ NHÂN");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(30, 60, 90));
        jLabel2.setText("Mã bác sĩ:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(30, 60, 90));
        jLabel3.setText("Tên bác sĩ:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(30, 60, 90));
        jLabel4.setText("Các phòng trực:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(30, 60, 90));
        jLabel5.setText("Các ngày nghỉ:");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(30, 60, 90));
        jLabel6.setText("Tài khoản:");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(30, 60, 90));
        jLabel7.setText("Mật khẩu:");

        lblDoctorId.setFont(new java.awt.Font("Segoe UI", 2, 20)); // NOI18N
        lblDoctorId.setForeground(new java.awt.Color(30, 60, 90));
        lblDoctorId.setText("Mã bác sĩ");

        lblDoctorName.setFont(new java.awt.Font("Segoe UI", 2, 20)); // NOI18N
        lblDoctorName.setForeground(new java.awt.Color(30, 60, 90));
        lblDoctorName.setText("Tên bác sĩ");

        lblRoomsAllowed.setFont(new java.awt.Font("Segoe UI", 2, 20)); // NOI18N
        lblRoomsAllowed.setForeground(new java.awt.Color(30, 60, 90));
        lblRoomsAllowed.setText("Các phòng trực");

        lblDatesOff.setFont(new java.awt.Font("Segoe UI", 2, 20)); // NOI18N
        lblDatesOff.setForeground(new java.awt.Color(30, 60, 90));
        lblDatesOff.setText("Các ngày nghỉ");

        lblUsername.setFont(new java.awt.Font("Segoe UI", 2, 20)); // NOI18N
        lblUsername.setForeground(new java.awt.Color(30, 60, 90));
        lblUsername.setText("Tài khoản");

        lblPassword.setFont(new java.awt.Font("Segoe UI", 2, 20)); // NOI18N
        lblPassword.setForeground(new java.awt.Color(30, 60, 90));
        lblPassword.setText("Mật khẩu");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addGap(69, 69, 69)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblDoctorName)
                                    .addComponent(lblDoctorId)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblPassword)
                                    .addComponent(lblUsername)
                                    .addComponent(lblDatesOff)
                                    .addComponent(lblRoomsAllowed))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lblDoctorId))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lblDoctorName))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(lblRoomsAllowed))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(lblDatesOff))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(lblUsername))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(lblPassword))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel lblDatesOff;
    private javax.swing.JLabel lblDoctorId;
    private javax.swing.JLabel lblDoctorName;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblRoomsAllowed;
    private javax.swing.JLabel lblUsername;
    // End of variables declaration//GEN-END:variables
}
