/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

import DTO.User;

/**
 *
 * @author PC
 */
public class pnlProfile extends javax.swing.JPanel {

    private final User user;

    /**
     * Creates new form pnlProfile
     *
     * @param user
     */
    public pnlProfile(User user) {
        initComponents();
        this.user = user;
    }

    @Override
    public void addNotify() {
        super.addNotify();
        String roomsAllowed = "<html>" + String.join("<br>", user.doctor().roomsAllowed().stream()
                .map(room -> room.roomName())
                .toList()) + "</html>";

        String daysOff = "<html>" + String.join(", ", user.doctor().daysOff().stream()
                .map(day -> String.valueOf(day.date()))
                .toList()) + "</html>";

        lblDoctorID.setText(String.valueOf(user.doctor().doctorID()));
        lblDoctorName.setText(user.doctor().doctorName());
        lblRoomsAllowed.setText(roomsAllowed);
        lblDaysOff.setText(daysOff);
        lblUsername.setText(user.username());
        lblPassword.setText(user.password());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblDoctorID = new javax.swing.JLabel();
        lblDoctorName = new javax.swing.JLabel();
        lblRoomsAllowed = new javax.swing.JLabel();
        lblDaysOff = new javax.swing.JLabel();
        lblUsername = new javax.swing.JLabel();
        lblPassword = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(240, 248, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(30, 60, 90));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("THÔNG TIN CÁ NHÂN");

        lblDoctorID.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        lblDoctorID.setForeground(new java.awt.Color(50, 50, 50));
        lblDoctorID.setText("Mã bác sĩ");

        lblDoctorName.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        lblDoctorName.setForeground(new java.awt.Color(50, 50, 50));
        lblDoctorName.setText("Tên bác sĩ");

        lblRoomsAllowed.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        lblRoomsAllowed.setForeground(new java.awt.Color(50, 50, 50));
        lblRoomsAllowed.setText("Các phòng trực");

        lblDaysOff.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        lblDaysOff.setForeground(new java.awt.Color(50, 50, 50));
        lblDaysOff.setText("Các ngày nghỉ");

        lblUsername.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        lblUsername.setForeground(new java.awt.Color(0, 102, 204));
        lblUsername.setText("Tài khoản");

        lblPassword.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        lblPassword.setForeground(new java.awt.Color(200, 0, 0));
        lblPassword.setText("Mật khẩu");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Mã bác sĩ:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("Tên bác sĩ:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("Các phòng trực:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setText("Các ngày nghỉ:");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 102, 204));
        jLabel6.setText("Tài khoản:");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(200, 0, 0));
        jLabel7.setText("Mật khẩu:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addGap(68, 68, 68)
                            .addComponent(lblDoctorID))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(64, 64, 64)
                            .addComponent(lblDoctorName))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel4)
                            .addGap(18, 18, 18)
                            .addComponent(lblRoomsAllowed))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(29, 29, 29)
                            .addComponent(lblDaysOff))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(65, 65, 65)
                            .addComponent(lblUsername))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(68, 68, 68)
                            .addComponent(lblPassword)))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel1)
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel2)
                        .addComponent(lblDoctorID))
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel3)
                        .addComponent(lblDoctorName))
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel4)
                        .addComponent(lblRoomsAllowed))
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel5)
                        .addComponent(lblDaysOff))
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel6)
                        .addComponent(lblUsername))
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel7)
                        .addComponent(lblPassword))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel lblDaysOff;
    private javax.swing.JLabel lblDoctorID;
    private javax.swing.JLabel lblDoctorName;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblRoomsAllowed;
    private javax.swing.JLabel lblUsername;
    // End of variables declaration//GEN-END:variables
}
