/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

import DAL.DayManager;
import DAL.ScheduleManager;
import DTO.Doctor;
import DTO.Schedule;
import java.time.DayOfWeek;
import java.time.LocalDate;
import java.util.Comparator;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author PC
 */
public class pnlSchedules extends javax.swing.JPanel {

    private final Doctor doctor;
    private final List<Schedule> schedules;
    private int weekIndex;

    /**
     * Creates new form pnlSchedules
     *
     * @param doctor
     */
    public pnlSchedules(Doctor doctor) {
        initComponents();
        schedules = ScheduleManager.getSchedules().stream()
                .filter(schedule -> schedule.doctor().equals(doctor))
                .toList();
        this.doctor = doctor;
        weekIndex = 1;
    }

    private LocalDate getStartOfWeek(int year, int month) {
        LocalDate firstDayOfMonth = LocalDate.of(year, month, 1);
        int daysToFirstMonday = firstDayOfMonth.getDayOfWeek().getValue() - DayOfWeek.MONDAY.getValue();

        LocalDate firstMonday = firstDayOfMonth.plusDays(-daysToFirstMonday);
        return firstMonday.plusDays((weekIndex - 1) * 7);
    }

    private List<Schedule> getSchedulesForWeek(LocalDate startOfWeek) {
        LocalDate endOfWeek = startOfWeek.plusDays(6);

        return schedules.stream()
                .filter(s -> !s.day().date().isBefore(startOfWeek) && !s.day().date().isAfter(endOfWeek))
                .sorted(Comparator.comparing(s -> s.day().date()))
                .toList();
    }

    private void tblSchedulesLoad() {
        LocalDate date = DayManager.getDays().get(0).date();
        LocalDate startOfWeek = getStartOfWeek(date.getYear(), date.getMonthValue());

        List<Schedule> schedulesForWeek = getSchedulesForWeek(startOfWeek);

        Object[] rowRooms = new Object[7];
        Object[] rowDays = new Object[7];

        for (Schedule schedule : schedulesForWeek) {
            int dayOfWeek = schedule.day().date().getDayOfWeek().getValue();
            rowRooms[dayOfWeek - 1] = schedule.room().roomName();
        }

        for (int i = 0; i < 7; i++) {
            rowDays[i] = startOfWeek.plusDays(i);

            if (rowRooms[i] == null) {
                rowRooms[i] = "";
            }
        }

        DefaultTableModel model = (DefaultTableModel) tblSchedules.getModel();
        model.setRowCount(0);
        model.addRow(rowDays);
        model.addRow(rowRooms);
    }

    private void lblLoad() {
        lblDoctor.setText(doctor.doctorName());
        lblWeek.setText("Tuần: " + weekIndex);
    }

    private void load() {
        tblSchedulesLoad();
        lblLoad();
    }

    @Override
    public void addNotify() {
        super.addNotify();
        load();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblDoctor = new javax.swing.JLabel();
        btnNext = new javax.swing.JButton();
        btnPrev = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSchedules = new javax.swing.JTable();
        lblWeek = new javax.swing.JLabel();

        setBackground(new java.awt.Color(240, 248, 255));

        lblDoctor.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblDoctor.setForeground(new java.awt.Color(30, 60, 90));
        lblDoctor.setText("Tên");

        btnNext.setBackground(new java.awt.Color(70, 130, 180));
        btnNext.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnNext.setForeground(new java.awt.Color(255, 255, 255));
        btnNext.setText("Tiếp theo >");
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });

        btnPrev.setBackground(new java.awt.Color(70, 130, 180));
        btnPrev.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnPrev.setForeground(new java.awt.Color(255, 255, 255));
        btnPrev.setText("< Trở về");
        btnPrev.setEnabled(false);
        btnPrev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrevActionPerformed(evt);
            }
        });

        tblSchedules.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tblSchedules.setForeground(new java.awt.Color(51, 51, 51));
        tblSchedules.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "<html>Thứ<br>Hai</html>", "<html>Thứ<br>Ba</html>", "<html>Thứ<br>Tư</html>", "<html>Thứ<br>Năm</html>", "<html>Thứ<br>Sáu</html>", "<html>Thứ<br>Bảy</html>", "<html>Chủ<br>Nhật</html>"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblSchedules.setRowHeight(60);
        tblSchedules.setShowGrid(true);
        jScrollPane1.setViewportView(tblSchedules);
        javax.swing.table.JTableHeader header = tblSchedules.getTableHeader();
        header.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 18));
        header.setPreferredSize(new java.awt.Dimension(100, 70));

        javax.swing.table.DefaultTableCellRenderer headerRenderer =
        (javax.swing.table.DefaultTableCellRenderer) header.getDefaultRenderer();

        headerRenderer.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        headerRenderer.setBackground(new java.awt.Color(70, 130, 180));
        headerRenderer.setForeground(new java.awt.Color(255, 255, 255));

        header.setDefaultRenderer(headerRenderer);

        lblWeek.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblWeek.setForeground(new java.awt.Color(30, 60, 90));
        lblWeek.setText("Tuần");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblDoctor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnPrev)
                .addGap(18, 18, 18)
                .addComponent(lblWeek)
                .addGap(18, 18, 18)
                .addComponent(btnNext)
                .addContainerGap())
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDoctor)
                    .addComponent(btnNext)
                    .addComponent(btnPrev)
                    .addComponent(lblWeek))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        // TODO add your handling code here:
        weekIndex++;
        load();
        btnPrev.setEnabled(true);
        if (weekIndex == 5) {
            btnNext.setEnabled(false);
        }
    }//GEN-LAST:event_btnNextActionPerformed

    private void btnPrevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrevActionPerformed
        // TODO add your handling code here:
        weekIndex--;
        load();
        btnNext.setEnabled(true);
        if (weekIndex == 1) {
            btnPrev.setEnabled(false);
        }
    }//GEN-LAST:event_btnPrevActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnPrev;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDoctor;
    private javax.swing.JLabel lblWeek;
    private javax.swing.JTable tblSchedules;
    // End of variables declaration//GEN-END:variables
}
