/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui;

import bll.DateUtils;
import bll.ScheduleManager;
import bll.YearMonthManager;
import dto.Doctor;
import dto.Schedule;
import java.time.LocalDate;
import java.time.YearMonth;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author PC
 */
public class pnlWeeklySchedule extends javax.swing.JPanel {

    private final Doctor doctor;
    private int weekIndex;

    private void tbl_lblLoad() {
        YearMonth ym = YearMonthManager.getYearMonth0();
        LocalDate weekStartDate = DateUtils.getWeekStartDate(ym.getYear(), ym.getMonthValue(), weekIndex);
        Object[] rowDates = ScheduleManager.getDatesForWeek(weekStartDate);

        List<Schedule> schedules = ScheduleManager.getSchedulesForWeek(doctor, weekStartDate);
        Object[] rowRooms = ScheduleManager.getRoomsForWeek(schedules);

        DefaultTableModel model = (DefaultTableModel) tbl.getModel();
        model.setRowCount(0);
        model.addRow(rowDates);
        model.addRow(rowRooms);

        lblWeek.setText("Tuần: " + weekIndex);
    }

    /**
     * Creates new form pnlWeeklySchedule
     *
     * @param doctor
     */
    public pnlWeeklySchedule(Doctor doctor) {
        initComponents();
        this.doctor = doctor;
        weekIndex = 1;
    }

    @Override
    public void addNotify() {
        super.addNotify();
        lblName.setText(doctor.name());
        tbl_lblLoad();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblName = new javax.swing.JLabel();
        btnNext = new javax.swing.JButton();
        lblWeek = new javax.swing.JLabel();
        btnPrev = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl = new javax.swing.JTable();

        setBackground(new java.awt.Color(240, 248, 255));

        lblName.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        lblName.setForeground(new java.awt.Color(30, 60, 90));
        lblName.setText("Tên");

        btnNext.setBackground(new java.awt.Color(70, 130, 180));
        btnNext.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        btnNext.setForeground(new java.awt.Color(255, 255, 255));
        btnNext.setText("Tiếp theo >");
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });

        lblWeek.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        lblWeek.setForeground(new java.awt.Color(30, 60, 90));
        lblWeek.setText("Tuần");

        btnPrev.setBackground(new java.awt.Color(70, 130, 180));
        btnPrev.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        btnPrev.setForeground(new java.awt.Color(255, 255, 255));
        btnPrev.setText("< Trở về");
        btnPrev.setEnabled(false);
        btnPrev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrevActionPerformed(evt);
            }
        });

        tbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Thứ Hai", "Thứ Ba", "Thứ Tư", "Thứ Năm", "Thứ Sáu", "Thứ Bảy", "Chủ Nhật"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl.setRowHeight(32);
        jScrollPane1.setViewportView(tbl);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnPrev)
                        .addGap(18, 18, 18)
                        .addComponent(lblWeek)
                        .addGap(18, 18, 18)
                        .addComponent(btnNext)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblName)
                    .addComponent(btnNext)
                    .addComponent(lblWeek)
                    .addComponent(btnPrev))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        // TODO add your handling code here:
        weekIndex++;
        tbl_lblLoad();

        if (weekIndex == 2) {
            btnPrev.setEnabled(true);
        }

        if (weekIndex == 5) {
            btnNext.setEnabled(false);
        }
    }//GEN-LAST:event_btnNextActionPerformed

    private void btnPrevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrevActionPerformed
        // TODO add your handling code here:
        weekIndex--;
        tbl_lblLoad();

        if (weekIndex == 4) {
            btnNext.setEnabled(true);
        }

        if (weekIndex == 1) {
            btnPrev.setEnabled(false);
        }
    }//GEN-LAST:event_btnPrevActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnPrev;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblWeek;
    private javax.swing.JTable tbl;
    // End of variables declaration//GEN-END:variables
}
